[package]
name = "json-parser"
version = "0.1.0"
authors = ["Vincent Hiribarren <vhiribarren@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[dev-dependencies]
clap = "3.0.0-beta.2"